language: R
sudo: false
cache: packages

matrix:
  include:
  - name: "Release R github"
    r: release
    env: bdverse='github'
    after_success:
      - Rscript -e 'covr::codecov()'
    r_github_packages:
      - bd-R/bdDwC
  - name: "Release R CRAN"
    r: release
    env: bdverse='CRAN'
  - name: "Release R github OSX"
    r: release
    env: bdverse='github'
    r_github_packages:
      - bd-R/bdDwC
      - force: TRUE
    os: osx
  - r: devel
  - r: oldrel
  - r: 3.4